spring:
  profiles:
    include: secret
  jpa:
    open-in-view: false
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create
  sql.init.mode: always

logging:
  level:
    org.hibernate:
      SQL: debug
      orm.jdbc.bind: trace
