spring:
  profiles:
    include: secret
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        highlight_sql: true

logging:
  level:
    org.hibernate.type.descriptor.sql: trace
